name: meu_portifolio
description: Esse projeto é uma tentativa de atrair a atenção de recrutadores de equipes maiores. Como parte do objetivo, tentarei demonstrar varias camadas de conhecimento nesse projeto web, com pretenção de que seja uma aplicação responsiva, construida baseando-se em boas praticas como Clean Code, arquitetura MVVM.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.5.0+6

environment:
  sdk: '>=3.0.0-94.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  package_info_plus: ^4.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  url_launcher: ^6.1.12
  flutter_animate: ^4.2.0+1
  seo_renderer: ^0.6.0
  firebase_storage: ^11.6.0
  open_file: ^3.3.2
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  generate: true


  assets:
    - assets/images/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/ArialMT.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/CedarvilleCursive-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf

    - family: Borel
      fonts:
        - asset: assets/fonts/Borel/Borel-Regular.ttf

    - family: Comic_Neue
      fonts:
        - asset: assets/fonts/Comic_neue/ComicNeue-Regular.ttf


    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf





  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
